"""Bridge between the Discover Agent's memory and external CLAUDE.md files.

Two directions:

- ``import_claude_md`` — copies a CLAUDE.md (or any Markdown notes file)
  into ``memory/heuristics/`` so the next reflection pass sees it. Useful for
  seeding the agent with what Claude Code, Cursor rules, or hand-written
  developer notes already know about the project.

- ``export_claude_md`` — writes a CLAUDE.md-style summary of the agent's
  current memory. Useful for handing context back to Claude Code or any
  other reader so they can start a fresh session pre-loaded with what the
  agent has learned.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .memory import Memory


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _imported_dest(memory: Memory, source: Path) -> Path:
    """Where an imported file lands inside ``memory/heuristics/``."""
    safe_stem = source.stem.replace(" ", "_")
    return memory.heuristics_dir / f"imported__{safe_stem}.md"


def import_claude_md(source: str | Path, memory: Memory) -> Path:
    """Copy a Markdown notes file into ``memory/heuristics/``.

    Overwrites any prior import from the same source. The next reflection
    pass will see the new content via the Memory tool and decide whether
    to keep it as-is, integrate it into other heuristic files, or remove it.

    Returns the path the content was written to.
    """
    src = Path(source)
    if not src.exists() or not src.is_file():
        raise FileNotFoundError(f"Cannot import: {src} does not exist or is not a file")

    dest = _imported_dest(memory, src)
    dest.parent.mkdir(parents=True, exist_ok=True)

    header = (
        f"<!-- Imported from `{src}` on {_now()} by discover-agent. "
        "Reviewed on the next reflection pass. -->\n\n"
    )
    body = src.read_text(encoding="utf-8")
    dest.write_text(header + body, encoding="utf-8")
    return dest


def export_claude_md(target: str | Path, memory: Memory) -> Path:
    """Write a CLAUDE.md-style summary of the agent's current memory.

    The output is a single Markdown file containing:
    - The current codebase heuristics (concatenated from
      ``memory/heuristics/``).
    - A short table of analyzed files grouped by language.

    Designed to be checked into a project as ``CLAUDE.md`` (or
    ``docs/CLAUDE.md``) so the next Claude Code / Cursor / human reader
    starts with the agent's accumulated context.

    Returns the path the file was written to.
    """
    out = Path(target)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Codebase notes",
        "",
        f"_Auto-generated by discover-agent on {_now()}. Edit freely; "
        "the agent will preserve or revise content on its next reflection pass._",
        "",
        "## Heuristics",
        "",
    ]

    heuristics = memory.heuristics_text().strip()
    lines.append(heuristics if heuristics else "_(none yet — run `discover-agent <path>` first)_")

    records = memory.all_files()
    if records:
        by_lang: dict[str, list[str]] = {}
        for r in records:
            by_lang.setdefault(r.language or "unknown", []).append(r.path)

        lines += ["", "## Files analyzed", ""]
        for lang in sorted(by_lang):
            paths = sorted(by_lang[lang])
            lines.append(f"- **{lang}** ({len(paths)})")
            for p in paths[:20]:
                lines.append(f"  - `{p}`")
            if len(paths) > 20:
                lines.append(f"  - … and {len(paths) - 20} more")

    lines += ["", "## Stats", ""]
    for k, v in memory.stats().items():
        lines.append(f"- {k}: {v}")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
